### ISSUE TITLE
How do I add comments in OCL?

### ISSUE THREAD

**Issue by burck1** [OctopusDeploy/Ocl#128]
How do I add comments in OCL? I tried to use the HCL syntax (using a "#" at the beginning of a line for example) but Octopus Deploy gives me the error:

> There was an error trying to parse the file '.octopus/FooBar/deployment_process.ocl' on the foobar branch. Please check that the OCL is valid. Parsing failure: unexpected '#'; expected end of input (Line 145, Column 1); recently consumed: } }

For example:

```
step "Do The Thing" {
  action {
  }
}

# step "Do The Other Thing" {
#   action {
#   }
# }
```

**Comment by aivanov-oneinc** [comment]
Same question.
I am cooking a template for octopus configuration. And the template is considered to be a valid OCL file. And template engine working with comment-like syntax to perform conditional generation:

```
#if (true)
variable "ProductName" {
    value "MyProduct" {}
}
#endif
```

**Comment by aivanov-oneinc** [comment]
The HSL language (which I understand the OCL is based on) is supporting comments as `#` `//` and even multiline `/**/`. It would be good to have it here too

**Comment by aivanov-oneinc** [comment]
Just to clarify. @droyad is this repo still alive? Is it reasonable to create any issues here? Or it would be better to contact OctopusDeploy support directly?

**Comment by droyad** [comment]
@aivanov-oneinc Yes it's still alive, we are using it internally. However we do not directly monitor the repos, but I see that that statement is missing on this repo.

The best bet for support is to go via out [support team](https://octopus.com/support)

Judging from the tests we never got to adding comment support.

The difficulty with doing so is that we read the file into a C# object and then write the file when something changes to the UI. That means that there is no easy way to preserve comments. We'd have to do some sort of merge with the AST, which could be tricky.

**Comment by aivanov-oneinc** [comment]
Thanks you for your response @droyad
